[local]
localhost

[mongodb]
mongodb.snlp.shop

[redis]
redis.snlp.shop

[mysql]
mysql.snlp.shop

[rabbitmq]snlp
rabbitmq.snlp.shop

[catalogue]
catalogue.snlp.shop

[user]
user.snlp.shop

[cart]
cart.snlp.shop

[shipping]
shipping.snlp.shop

[payment]
payment.snlp.shop

[frontend]
frontend.snlp.shop

[private-key-demo]
172.31.37.172